// Action types for customer address
export const ADD_CUSTOMER_ADDRESS_REQUEST = 'ADD_CUSTOMER_ADDRESS_REQUEST';
export const ADD_CUSTOMER_ADDRESS_SUCCESS = 'ADD_CUSTOMER_ADDRESS_SUCCESS';
export const ADD_CUSTOMER_ADDRESS_FAILURE = 'ADD_CUSTOMER_ADDRESS_FAILURE';
